version: "3.5"

# Development environment override
services:
  event_registration_php:
    build:
      context: ./
      target: app_php_dev
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway

  event_registration_nginx:
    volumes:
      - ./public:/srv/app/public:ro
      - ./docker/nginx/templates:/etc/nginx/templates

  event_registration_database:
    ports:
      - target: 5432
        published: ${POSTGRES_PORT:-5432}
        protocol: tcp
